# Site settings
title: JScottGraves' Code Fight Club
email: scottgrvs@hiregraves.net
description: > # this means to ignore newlines until "baseurl:"
  JScottGraves' musings about code, math, and whatever.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://JScottGraves.github.io" # the base hostname & protocol for your site
twitter_username: jsgcodes
github_username:  JScottGraves

# Build settings
markdown: kramdown
